apiVersion: batch/v1
kind: CronJob
metadata:
  name: podchecker
  namespace: cron
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-reader
          restartPolicy: Never
          containers:
          - name: podchecker
            image: keithkwok1904/podchecker:latest
            imagePullPolicy: Always
            env:
            - name: MAILPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailpasswd
                  key: mailpassword
            - name: SENDER
              value: "keithkwok1904@gmail.com"
            - name: RECEIVER
              value: "keithkwok1904@gmail.com"
            volumeMounts:
            - name: log-volume
              mountPath: /k8slog
          volumes:
          - name: log-volume
            nfs:
              server: k8slogccgc5504.file.core.windows.net
              path: /k8slogccgc5504/k8slog

