apiVersion: v1
kind: Pod
metadata:
  name: logstreamer
  namespace: cron
spec:
  containers:
  - name: logstreamer
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - while true; do echo ""; echo "Showing last 10 records:"; tail /k8slog/report.log; sleep 10; done;
    volumeMounts:
    - name: log-volume
      mountPath: /k8slog
  volumes:
  - name: log-volume
    nfs:
      server: k8slogccgc5504.file.core.windows.net
      path: /k8slogccgc5504/k8slog
      readOnly: true
