apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuck
  labels:
    app: stuck
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stuck
  template:
    metadata:
      labels:
        app: stuck
    spec:
      containers:
      - name: stuck
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nothing
            topologyKey: "kubernetes.io/hostname"
