apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apple.fullname" . }}
  labels:
    {{- include "apple.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apple.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
